=== delyan-nikolov-1992/Telerik-Academy/Telerik Academy 2013-2014/12. Databases/13. XML Basics/XML-Basics/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:students" targetNamespace="urn:students">
  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="student" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="student">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="sex"/>
        <xs:element ref="birth-date"/>
        <xs:element ref="phone"/>
        <xs:element ref="email"/>
        <xs:element ref="course"/>
        <xs:element ref="specialty"/>
        <xs:element ref="faculty-number"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="taken-exams">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="exam-name"/>
        <xs:element ref="tutor"/>
        <xs:element ref="score"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="sex" type="xs:string"/>
  <xs:element name="birth-date" type="xs:date"/>
  <xs:element name="phone" type="xs:string"/>
  <xs:element name="email" type="xs:string"/>
  <xs:element name="course" type="xs:string"/>
  <xs:element name="specialty" type="xs:string"/>
  <xs:element name="faculty-number" type="xs:string"/>
  <xs:element name="exam-name" type="xs:string"/>
  <xs:element name="tutor" type="xs:string"/>
  <xs:element name="score" type="xs:decimal"/>
</xs:schema>

=== delyan-nikolov-1992/Telerik-Academy/Telerik Academy 2013-2014/12. Databases/13. XML Basics/XML-Basics/students.xml
<?xml version="1.0" encoding="utf-8"?>
<students xmlns="urn:students" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="urn:students file://./students.xsd">
  <student>
    <name>Trifon Zarezan</name>
    <sex>Male</sex>
    <birth-date>1994-04-08</birth-date>
    <phone>0888121464</phone>
    <email>crazy_man@gmail.com</email>
    <course>Second</course>
    <specialty>Computer science</specialty>
    <faculty-number>191754196</faculty-number>
    <taken-exams>
      <exam>
        <exam-name>OOP</exam-name>
        <tutor>Michael Schweinsteiger</tutor>
        <score>4.54</score>
      </exam>
      <exam>
        <exam-name>Databases</exam-name>
        <tutor>Ivaylo Kenov</tutor>
        <score>6.00</score>
      </exam>
    </taken-exams>
  </student>
  <student>
    <name>Saint Patrick</name>
    <sex>Male</sex>
    <birth-date>1960-12-12</birth-date>
    <phone>0897125464</phone>
    <email>dude1960@gmail.com</email>
    <course>Frrst</course>
    <specialty>Computer science</specialty>
    <faculty-number>191754197</faculty-number>
    <taken-exams>
      <exam>
        <exam-name>OOP</exam-name>
        <tutor>Michael Schweinsteiger</tutor>
        <score>3.54</score>
      </exam>
      <exam>
        <exam-name>Databases</exam-name>
        <tutor>Ivaylo Kenov</tutor>
        <score>3.00</score>
      </exam>
    </taken-exams>
  </student>
</students>
